feat: created a back end user
SuelenLaffinWarren/ApiEverest pull request #1
Opened 2022-11-18 17:21 UTC by SuelenLaffinWarren

[Link do card](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-984)

✅ criação de um CRUD para entity Customer;
✅ dados salvos na lista em memória;
✅ utilização do fluent validation;
✅ status retornando conforme solicitado;
✅ utilizando interface;

2022-11-18 18:42 UTC, gregoryzimmerwarren requested changes
- Acho importante você se atentar com os espaçamentos para não deixar demais.

- Acredito que tu tem uma pasta Entities dentro de outra chamada Models. Confirma isso, se tiver pode apagar Models e deixar só Entities mesmo.

- Tu vai ver que no construtor do Customer e no Validador no método IsValidCpf eu coloquei um .FormatCpf, acho interessante tu criar uma extension de string para fazer a formatação. Como nesse card ainda não tem uma arquitetura, pode deixar dentro da pasta Entities.

- Além disso deixei comentários e sugestões, qualquer dúvida pode entrar em contato.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/ApiEverest.sln
> +﻿
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
Realizar todas as importações e nulidades necessárias.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +    <Folder Include="Interfaces\" />
```suggestion
	  <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +    <Folder Include="Interfaces\" />
Acredito que os outros packages não estavam sendo usados, e a pasta não existia. Verificar se o código quebrou com a retirada destes.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +using Microsoft.AspNetCore.Mvc;
Remover usings não utilizados.

Uma dica é o atalho Ctrl+R+G

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        public CostumerController(ICustomerService customerService)
```suggestion
        private readonly ICustomerService _customerService;
        
        public CostumerController(ICustomerService customerService)
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        }
Rever este método. Ele também vai ser um IActionResult

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +                : NotFound($"Customer não encontrado para o Id: {id}");
```suggestion          
            try
            {
                var response = _customerService.GetById(id);
                return Ok(response);
            }
            catch (ArgumentNullException exception)
            {
                var message = exception.InnerException?.Message ?? exception.Message;

                return NotFound(message);
            }
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +                : NotFound($"Customer não encontrado para o Id: {id}");
Aqui na controller a gente não pode ter lógica, então temos apenas os try catchs. Tu tem que implementar no teu service as Exceptions que vão retornar em caso de erro, para serem capturadas nos catchs se necessário.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +                : NotFound($"Customer não encontrado para o Id: {id}");
Recomendo rever todos os métodos.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +                ? Created("Dados inseridos com sucesso", customerModel.Id)
```suggestion
                ? Created("Id: ", customerModel.Id)
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +                ? Ok()
```suggestion
                ? NoContent()
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Models/Entities/BaseEntity.cs
> +    }
```suggestion
    public interface IEntity
    {
        long Id { get; set; }
    }
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Models/Entities/CustomerEntity.cs
> +    public class CustomerEntity : BaseEntity
```suggestion
    public class Customer : IEntity
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Models/Entities/CustomerEntity.cs
> +        }
```suggestion
        public Customer(
           string fullName,
           string email,
           string emailConfirmation,
           string cpf,
           string cellphone,
           DateTime dateOfBirth,
           bool emailSms,
           bool whatsapp,
           string country,
           string city,
           sring address;
           string postalCode,
           int number)
        {
            FullName = fullName;
            Email = email;
            EmailConfirmation = emailConfirmation;
            Cpf= cpf.FormatCpf();
            Cellphone = cellphone;
            Number= number;
            DateOfBirth = dateOfBirth;
            EmailSms = emailSms;
            Whatsapp= whatsapp;
            Country= country;
            City= city;
            PostalCode= postalCode; 
        }
        
        public string FullName { get; set; }
        public string Email { get; set; }
        public string EmailConfirmation { get; set; }
        public string Cpf { get; set; }
        public string Cellphone { get; set; }
        public int Number { get; set; }
        public DateTime DateOfBirth { get; set; }
        public bool EmailSms { get; set; }
        public bool Whatsapp { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Models/Entities/CustomerEntity.cs
> +        }
Sempre colocamos o construtor antes das propriedades da classe.

Cuidado com os tipos e com as propriedades solicitadas.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Models/Entities/CustomerEntity.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +    {
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +        // Add services to the container.
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +        // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +        // Configure the HTTP request pipeline.
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/ICustomerService.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/ICustomerService.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/ICustomerService.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/ICustomerService.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        private readonly List<CustomerEntity> listCustomers = new List<CustomerEntity>();
```suggestion
        private readonly List<CustomerEntity> listCustomers = new();
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        private readonly List<CustomerEntity> listCustomers = new List<CustomerEntity>();
O AspNet permite que você não precise repetir a tipagem após o new.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            listCustomers.RemoveAt(index);
```suggestion
           var customer = GetById(id);
           listCustomers.Remove(customer);
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            listCustomers.RemoveAt(index);
Assim você se aproveita de outro método já existente e caso o Id não existe o erro vai estourar direto pelo método do GetById

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            return true;
Conforme regra de negócio do card, você tem que adicionar validação para impedir de adicionar/atualizar um Customer com e-mail e Cpf duplicado

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +          return listCustomers.Find(customer => customer.Id == id);
Aqui usa o FirstOrDefault no lugar do Find e não retorna direto a pesquisa, salva primeiro em uma variável e depois retorna ela, facilita para fazer debug.

Também precisa criar uma exeption para caso venha nulo, dessa forma:

if (customer == null)
                throw new ArgumentNullException($"Customer with id: {id} was not found");

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            }
Utilizando as exceptions teu erro já vai vir do GetById, então não precisa dessa parte.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        }
Rever teu método, é mais interessante ter pesquisas separadas para email e cpf, porque você consegue lançar exceptions específicas para cada caso.

Além disso da forma que está você está dizendo que se encontrar email ou cpf já na lista você vai continuar com o Update. O correto é se encontrar email e for de outro id lança exception. Mesma coisa para cpf.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/ICustomerService.cs
> +    public interface ICustomerService
Fazendo uso das exceptions e try catch teus métodos bool vão se tornar todos void.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +                .MinimumLength(5).WithMessage("Minimum length must be 5 caracteres");
Trocar os NotNull por NotEmpty, este último já vai englobar o primeiro. Também, não há necessidade de mensagem dai para os NotEmpty, eles já tem mensagem automática. MinimunLength também tem automática.

Rever em todas as rules.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +                .Length(11).Must(isValidCpf).WithMessage("Cpf is invalid");
```suggestion
                .Length(11)
                .Must(isValidCpf)
                .WithMessage("Cpf is invalid");
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +            if (cpf.Distinct().Count() == 1) return false;
```suggestion
            cpf = cpf.FormatCpf();

            if (cpf.Length != 11)
               return false;                
                
            if (cpf.Distinct().Count() == 1)
               return false;
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +            }
```suggestion
                rest = 0;
            else
                rest = 11 - rest;

```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +            }
Quando if ou else só tem uma linha de ação não precisa de { }

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +            }
Rever de acordo com o último comentário.

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +
```suggestion
```

2022-11-18 18:42 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +    }
Acho interessante pensar em um validador de Cellphone e de PostalCode também.

2022-11-21 13:21 UTC, LuanFortunatoW commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        [HttpDelete]
```suggestion
        [HttpDelete("{id}")]
```

2022-11-21 13:21 UTC, LuanFortunatoW commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +                    return BadRequest("O usuário já existe");
O ideal é todas as verificações serem feitas na service, daí você pode adicionar uma nova exception lá e ir aninhado quanto catch você precisar pra retornar o erro

2022-11-21 13:21 UTC, LuanFortunatoW commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        public IActionResult Update(CustomerEntity customerModel)
```suggestion
        public IActionResult Update(CustomerEntity customerEntity )
```

2022-11-21 13:21 UTC, LuanFortunatoW commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        public ActionResult Create([FromBody]CustomerEntity customerModel)
```suggestion
        public ActionResult Create([FromBody]CustomerEntity customerEntity)
```

2022-11-21 13:21 UTC, LuanFortunatoW commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        }
```suggestion
        public void Create(CustomerEntity model)
        {
            model.Id = listCustomers.LastOrDefault()?.Id + 1 ?? 1;

            if(listCustomers.Any() || customerDuplicate(model))
            {
                throw new ArgumentException();
            }

            listCustomers.Add(model);
        }
```
Ao invés de você fazer esses métodos retornando um booleano pra fazer a verificação se saiu tudo corretamente o ideal é não retornar nada e tratar isso com as exceções a aqui e resgatar elas na controller com o try catch

2022-11-21 13:21 UTC, LuanFortunatoW commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            listCustomers.RemoveAt(index);
Mesmo comentário acima

2022-11-21 13:21 UTC, LuanFortunatoW commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            {
Mesmo comentário acima

2022-11-21 20:03 UTC, SuelenLaffinWarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            {
correções aplicadas

2022-11-22 13:00 UTC, gregoryzimmerwarren requested changes
Deixei novos comentários

2022-11-22 13:00 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/BaseEntity.cs
> +    }
```suggestion
    public interface IEntity
    {
        long Id { get; set; }
    }
```

2022-11-22 13:00 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/CustomerEntity.cs
> +    public class CustomerEntity : BaseEntity
```suggestion
    public class CustomerEntity : IEntity
```

2022-11-22 13:00 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/CustomerEntity.cs
> +
```suggestion
```

2022-11-22 13:00 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/CustomerEntity.cs
> +
```suggestion
        public string PostalCode { get; set; }
```

2022-11-22 13:00 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +
```suggestion
        public static string CpfFormatter(this string cpf) 
```

2022-11-22 13:00 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +    }
```suggestion
        }
    }
```

2022-11-22 13:00 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +            return Convert.ToUInt64(cpf).ToString(@"000\.000\.000\-00");
Não entendi muito bem tua formatação, no final o cpf sai formatado, por exemplo,  111.111.111-11 ?

2022-11-22 13:00 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +}
```suggestion
        app.Run();
```

2022-11-22 13:00 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            if (listCustomers.Any(c => c.Email == customerCreate.Email))
```suggestion
        {
            if (listCustomers.Any(c => c.Email == customerCreate.Email))
```

2022-11-22 13:20 UTC, SuelenLaffinWarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +            return Convert.ToUInt64(cpf).ToString(@"000\.000\.000\-00");
sim, ele sai certinho formatado, igual o seu exemplo

2022-11-22 14:40 UTC, gregoryzimmerwarren requested changes
Deixei novos comentários.

Qualquer dúvida estou a disposição.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +  </ItemGroup>
Da uma olhada se você não tem uma pasta que precise ser excluída.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
```suggestion
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
Acredito que só este package vai estar sendo usado. Verifica se vai dar problema por excluir os outros.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +            catch(ArgumentNullException exception)
```suggestion
            catch(ArgumentException exception) 
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +            catch(ArgumentNullException exception)
Conforme teu service.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
Conforme o @LuanFortunatoW comentou, faz tua lógica no service e aqui apenas os try catchs, dai podes utilizar dois aqui, um catch pro ArgumentNullException e outro pro ArgumentException

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        }
```suggestion
            }           
        }
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/CustomerEntity.cs
> +        string emailSms,
```suggestion
        bool emailSms,
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/CustomerEntity.cs
> +        public string EmailSms { get; set; }
```suggestion
        public bool EmailSms { get; set; }
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +            return Convert.ToUInt64(cpf).ToString(@"000\.000\.000\-00");
Eu testei teu programa e não está funcionando aqui.

Te sugiro usar o seguinte:
return cpf.Trim().Replace(".", "").Replace(",", "").Replace("-", "").Replace(" ", "");

Assim ele vai retirar qualquer espaço vazio antes, depois ou dentro da string, e vai remover . , e -

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +            return Convert.ToUInt64(cpf).ToString(@"000\.000\.000\-00");
```suggestion
            return cpf.Trim().Replace(".", "").Replace(",", "").Replace("-", "").Replace(" ", "");
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +        app.Run();
Usa o atalho Ctrl + K + D para corrigir a indentação.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            }
```suggestion
            if (listCustomers.Any(c => c.Email == customerCreate.Email))
                throw new ArgumentException("Existing email");
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            }
Como teu if tem apenas um comando não precisa das { }. Aplicar nos demais.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            customerCreate.Id = listCustomers.LastOrDefault()?.Id + 1 ?? 1;
```suggestion
            }
            
            customerCreate.Id = listCustomers.LastOrDefault()?.Id + 1 ?? 1;
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        if (response == null) throw new ArgumentNullException($"Customer with id: {id} was not found");
```suggestion
        if (response == null)
           throw new ArgumentNullException($"Customer with id: {id} was not found");
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            if(listCustomers.Any(customer => customer.Email == model.Email))
```suggestion
            }
            
            if(listCustomers.Any(customer => customer.Email == model.Email))
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            return false;
```suggestion
            }
            
            return false;
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        }
```suggestion
        public void Delete(long id)
        {
           var customer = GetById(id);
           listCustomers.Remove(customer);
        }
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        }
Utilizando os try catchs na controller não tem mais a necessidade do booleano.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        }
Rever método conforme o comentário do Delete.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Services/ICustomerService.cs
> +        bool Delete(long id);
```suggestion
        void Update(CustomerEntity model);
        void Delete(long id);
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +                .MinimumLength(5).WithMessage("Minimum length must be 5 caracteres");
```suggestion                
                .MinimumLength(5);
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +                .MinimumLength(5).WithMessage("Minimum length must be 5 caracteres");
NotEmpty e MinimumLength possuem mensagens padronizadas pelo FluentValidation, então não há a necessidade de mensagem.

Rever nos demais.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +            RuleFor(c => c.PostalCode)
```suggestion
                .MaximumLength(16);
                
            RuleFor(c => c.PostalCode)
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +        private static bool OverAgeCustomer(DateTime dateOfBirth)
```suggestion
                .MaximumLength(9);
        }
        
        private static bool OverAgeCustomer(DateTime dateOfBirth)
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +            if (cpf.Length != 11)
```suggestion
            int sum = 0;
            
            cpf = cpf.Trim();
            cpf = cpf.Replace(".", "").Replace("-", "");
            
            if (cpf.Length != 11)
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +            if (cpf.Length != 11)
Substitiu a tua formatação manual pela extension.

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +                rest = 11 - rest;
```suggestion
            else
                rest = 11 - rest;
                
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Validators/CustomerRulesValidator.cs
> +            Digit = Digit + rest.ToString();
```suggestion
                rest = 11 - rest;
                
            Digit = Digit + rest.ToString();            
```

2022-11-22 14:40 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +            return Convert.ToUInt64(cpf).ToString(@"000\.000\.000\-00");
Acho interessante pensar em um extension para corrigir a formatação de Cellphone e de PostalCode também.

2022-11-22 14:45 UTC, SuelenLaffinWarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
deu problema sim, pq eu exclui e ao fazer o push deu um monte de erro, por causa de coisas que precisavam ser importadas

2022-11-22 16:18 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
Deixa só esses dois aqui:

<PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" / >
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" / >

Usa o atalho Ctrl + Shift + B e vai no erro que aparecer e exclui aquela importação lá do Customer que não precisa.

2022-11-23 12:40 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        }
```suggestion
        }
        
```

2022-11-23 12:41 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        public ActionResult Create([FromBody]CustomerEntity customerEntity)
```suggestion
        public IActionResult Create([FromBody]CustomerEntity customerEntity)
```

2022-11-23 12:42 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-23 12:44 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Entities/CustomerEntity.cs
> +        {
```suggestion
        public CustomerEntity(
            string fullName,
            string email,
            string emailConfirmation,
            string cpf,
            string cellphone,
            DateTime dateOfBirth,
            bool emailSms,
            bool whatsapp,
            string country,
            string city,
            string postalCode,
            int number
        )
        {
```

2022-11-23 12:44 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Entities/CustomerEntity.cs
> +        }
```suggestion
        }
        
```

2022-11-23 12:45 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +}
```suggestion
namespace ApiEverest.Entities
{
    public static class StringExtensions
    {
        public static string CpfFormatter(this string cpf)
        {
            return cpf.Trim().Replace(".", "").Replace("-", "");
        }
    }
}
```

2022-11-23 12:47 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +using Microsoft.AspNetCore.Mvc;
```suggestion
```
using não utilizado.

2022-11-23 12:50 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        public bool customerDuplicate(CustomerEntity model)
```suggestion
        public bool CustomerDuplicate(CustomerEntity model)
```

2022-11-23 12:54 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +        }
```suggestion
        {
            if (listCustomers.Any(customer => customer.Cpf == model.Cpf))
                throw new ArgumentException("Did not found customer for CPFs");

            if (listCustomers.Any(customer => customer.Email == model.Email))
                throw new ArgumentException("Did not found customer for Email");
        }
```

2022-11-23 12:56 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +
```suggestion
            CustomerDuplicate(customerCreate);
```

2022-11-23 12:58 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +            }
```suggestion
            CustomerDuplicate(updateCustomer);
```

2022-11-23 14:12 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-23 14:13 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-23 14:13 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-11-23 14:14 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Entities/CustomerEntity.cs
> +﻿
```suggestion
```

2022-11-23 14:15 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +
```suggestion
```

2022-11-23 14:15 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Services/CustomerService.cs
> +
```suggestion
```

2022-11-23 15:03 UTC, gregoryzimmerwarren requested changes
Deixei novos comentários. Qualquer coisa só chamar.

2022-11-23 15:03 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +            return cpf.Trim().Replace(".", "").Replace("-", "");
```suggestion
            return cpf.Trim().Replace(".", "").Replace("-", "").Replace(",", "").Replace(" ", "");
```

2022-11-23 15:03 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +            return cpf.Trim().Replace(".", "").Replace("-", "");
Apenas para garantir qualquer possível forma de digitação que o usuário venha a fazer.

2022-11-23 15:03 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Entities/StringExtensions.cs
> +            return cpf.Trim().Replace(".", "").Replace("-", "");
Te recomendo fazer também:

public static string FormatCellphone(this string cellphone)
    {
        return cellphone.Trim().Replace("(", "").Replace(")", "").Replace("-", "").Replace(".", "").Replace(",", "").Replace(" ", "");
    }
    
public static string FormatPostalCode(this string postalCode)
    {
        return postalCode.Trim().Replace("-", "").Replace(".", "").Replace(",", "").Replace(" ", "");
    }

E usar lá no teu entity.

2022-11-23 15:03 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +		<PackageReference Include="FluentValidation" Version="11.3.0" />
```suggestion
```

2022-11-23 16:20 UTC, gregoryzimmerwarren approved these changes

2022-11-23 16:29 UTC, santosclaudinei-warren approved these changes

2022-12-13 18:48 UTC, merged