feat: onion architecture
SuelenLaffinWarren/ApiEverest pull request #2
Opened 2022-11-24 11:53 UTC by SuelenLaffinWarren

[Link do card](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-985)

✅ Criação do AppServices;
✅ Criação do DomainModels;
✅ Criação do DomainServices;
✅ Validações estão na camada de AppServices;

2022-11-24 14:33 UTC, LuanFortunatoW commented on ApiEverest/AppServices/Services/ICostumerAppService.cs
> +    public interface ICostumerAppService
```suggestion
    public interface ICustomerAppService
```

2022-11-24 14:33 UTC, LuanFortunatoW commented on ApiEverest/AppServices/Services/CostumerAppService.cs
> +    public class CostumerAppService : ICostumerAppService
```suggestion
    public class CustomerAppService : ICustomerAppService
```

2022-11-25 16:39 UTC, santosclaudinei-warren commented on ApiEverest/AppServices/AppServices.csproj
> +    <Nullable>enable</Nullable>
Remover e realizar os imports explicitamente com usings
```suggestion
```

2022-11-25 16:39 UTC, santosclaudinei-warren commented on ApiEverest/DomainModels/DomainModels.csproj
> +    <Nullable>enable</Nullable>
Remover e realizar os imports explicitamente com usings
```suggestion
```

2022-11-25 16:40 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/DomainServices.csproj
> +    <Nullable>enable</Nullable>
Remover e realizar os imports explicitamente com usings
```suggestion
```

2022-11-25 16:46 UTC, santosclaudinei-warren commented on ApiEverest/AppServices/Services/CostumerAppService.cs
> +        private readonly ICustomerAppService _customerAppService;
```suggestion
        private readonly ICustomerService _customerService;
```
Deveria estar chamando a camada de servico

2022-11-25 16:48 UTC, santosclaudinei-warren commented on ApiEverest/AppServices/Services/CostumerAppService.cs
> +        public void Create(CustomerEntity customerEntity)
```suggestion

        public void Create(CustomerEntity customerEntity)
```

2022-11-25 16:52 UTC, LuanFortunatoW commented on ApiEverest/AppServices/Services/CostumerAppService.cs
> +    {
Faltou gerar um construtor para fazer a injeção da instancia de ICustomerService

2022-11-28 11:54 UTC, gregoryzimmerwarren requested changes
Deixei um comentário. Qualquer dúvida estou a disposição.

2022-11-28 11:54 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/AppServices.csproj
> +    <PackageReference Include="FluentValidation" Version="11.2.1" />
```suggestion
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.1" />
```

2022-11-29 11:57 UTC, gregoryzimmerwarren approved these changes
Deixei só mias uma sugestão para remoção de uma linha. Mas acredito que da minha parte seja isso. Já vou deixar aprovado. Só ver também os comentários dos demais colegas.

2022-11-29 11:57 UTC, gregoryzimmerwarren commented on ApiEverest/DomainModels/Entities/CustomerEntity.cs
> +using System;
```suggestion
using System;
```

2022-12-13 18:51 UTC, santosclaudinei-warren commented on ApiEverest/AppServices/Services/ICostumerAppService.cs
> +        void Create(CustomerEntity model);
```suggestion
        long Create(CustomerEntity model);
```

2022-12-13 19:51 UTC, SuelenLaffinWarren commented on ApiEverest/AppServices/Services/ICostumerAppService.cs
> +        void Create(CustomerEntity model);
ajustes feitos

2022-12-13 20:26 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/AppModels.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```

2022-12-13 20:27 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +        {
```suggestion
        )
        {
```

2022-12-13 20:27 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +        }
```suggestion
        }
        
```

2022-12-13 20:27 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +
```suggestion
```

2022-12-13 20:28 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +        {
```suggestion
        )
        {
```

2022-12-13 20:28 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +        }
```suggestion
        }
        
```

2022-12-13 20:28 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +
```suggestion
```

2022-12-13 20:29 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +
```suggestion
```

2022-12-13 20:33 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +
```suggestion
```

2022-12-13 20:35 UTC, santosclaudinei-warren commented on ApiEverest/AppServices/Profile/CustomerProfile.cs
> +
```suggestion
```

2022-12-13 20:35 UTC, santosclaudinei-warren commented on ApiEverest/AppServices/Profile/CustomerProfile.cs
> +
```suggestion
```

2022-12-13 21:02 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        private readonly IMapper _mapper;
AutoMapper faz parte desse desafio?

2022-12-13 21:04 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
>          private readonly ICustomerService _customerService;
Não está utilizando a camada de App Services. Precisa utilizar.

2022-12-13 21:35 UTC, santosclaudinei-warren commented on ApiEverest/Dtos/CustomerResult.cs
> +}
vazio?

2022-12-13 21:35 UTC, santosclaudinei-warren commented on ApiEverest/Dtos/CustomerResult.cs
> +}
Deveria estar na camada AppModels se for um DTO que pretende utiliza-lo.

2022-12-14 11:38 UTC, SuelenLaffinWarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
>          private readonly ICustomerService _customerService;
Ajustes feitos

2022-12-14 12:18 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +using DomainServices.Services;
```suggestion
﻿using AppServices.Services;
using DomainModels.Entities;
```

Para facilitar a remoção dos using não utilizados usamos o comando CTRL + R + G

2022-12-14 12:18 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +
```suggestion
```

2022-12-14 12:21 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
>                  return Created("Id:", customerEntity.Id);
```suggestion
                return Created("Id:", customerId");
```
Utilizar o retorno do método Create de _customerAppService

2022-12-14 12:29 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
> +
```suggestion
```

2022-12-14 12:30 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
> +
```suggestion
```

2022-12-14 12:31 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
>          }
```suggestion
        }
        
```

2022-12-14 12:31 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
>          }
```suggestion
        }
        
```

2022-12-14 12:32 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
>          }
```suggestion
        }
        
```

2022-12-14 12:32 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
>          }
```suggestion
        }
        
```

2022-12-14 12:33 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
>          }
```suggestion
        }
        
```

2022-12-14 12:33 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
>          private readonly List<CustomerEntity> listCustomers = new();
```suggestion
        private readonly List<CustomerEntity> listCustomers = new();
        
```

2022-12-14 12:36 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
```suggestion
```
Não está sendo utilizado.

2022-12-14 13:07 UTC, SuelenLaffinWarren commented
ajustes realizados

2022-12-15 12:07 UTC, LuanFortunatoW approved these changes

2022-12-15 15:04 UTC, santosclaudinei-warren approved these changes

2022-12-16 14:10 UTC, merged