Feat/ev 986/best practices api
SuelenLaffinWarren/ApiEverest pull request #3
Opened 2022-12-02 16:54 UTC by SuelenLaffinWarren

[Link do Card](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-986)

✅ Mapeamento feito na camada de aplicação;

✅ Uso do AutoMapper;

✅ Criação de DTOS;

2022-12-06 20:37 UTC, gregoryzimmerwarren requested changes
Deixei alguns comentários. Qualquer dúvida estou a disposição.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/AppModels.csproj
> +    <Nullable>enable</Nullable>
```suggestion
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/AppModels.csproj
> +    <Nullable>enable</Nullable>
Verificar importações e nulidades.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +namespace AppModels
```suggestion
namespace AppModels
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +      )
Verifica a indentação com o atalho Ctrl+K+D.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +        public string EmailConfirmation { get; set; }
```suggestion
        public string Email { get; set; }
        public string EmailConfirmation { get; set; }
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +        public long Id { get; set; }
```suggestion
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +        public long Id { get; set; }
Não é uma informação que o usuário irá passar.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerResult.cs
> +namespace AppModels
```suggestion
﻿namespace AppModels
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerResult.cs
> +        protected CustomerResult() { }
```suggestion
        protected CustomerResult() { }
        
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerResult.cs
> +    public class CustomerResult
Seguir um padrão na nomenclatura. Acrescentar Dto no nome dessa classe, ou retirar no Create e no Update (o que eu sugiro fazer).

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +namespace AppModels
```suggestion
namespace AppModels
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerResult.cs
> +    )
Ctrl+K+D

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +      )
Ctrl+K+D

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +        public string EmailConfirmation { get; set; }
```suggestion
        public string Email { get; set; }
        public string EmailConfirmation { get; set; }
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +        public long Id { get; set; }
```suggestion
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/AppServices.csproj
> +    <PackageReference Include="AutoMapper" Version="12.0.0" />
```suggestion
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Profiles/CustomerProfile.cs
> +    }
```suggestion
using DomainModels.Entities;

namespace ApiEverest.Profiles
{
    public class CustomerProfile : Profile
    {
        public CustomerProfile() 
        {
            CreateMap<CustomerCreateDto, CustomerEntity>();
            CreateMap<CustomerUpdateDto, CustomerEntity>();
            CreateMap<CustomerEntity, CustomerResult>();
        }
    }
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Services/CustomerAppService.cs
> +        }
```suggestion
        public void Create(CustomerCreateDto customerCreateDto)
        {           
            var customerCreateDto = _mapper.Map<CustomerEntity>(customerCreateDto);
            _customerService.Create(customerCreateDto );
        }
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Services/CustomerAppService.cs
> +            _customerService.Update(_customerUpdateDto);
```suggestion
        public void Update(CustomerUpdateDto customerUpdateDto)
        {
            var customerUpdateDto = _mapper.Map<CustomerEntity>(customerUpdateDto);
            _customerService.Update(customerUpdateDto);
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerCreateValidator.cs
> +using FluentValidation;
```suggestion
using DomainModels.Entities;
using FluentValidation;
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerCreateValidator.cs
> +                .EmailAddress().WithMessage("Invalid Email format");
```suggestion
                .EmailAddress(EmailValidationMode.Net4xRegex)
                .WithMessage("Invalid Email format");
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerCreateValidator.cs
> +                .EmailAddress().WithMessage("Invalid Email format");
Alterar a mensagem para deixar mais claro para o usuário qual o formato válido.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerCreateValidator.cs
> +
```suggestion

RuleFor(customer => customer)
            .Must(customer => customer.EmailConfirmation == customer.Email);
            
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerCreateValidator.cs
> +
Garante que o email e o emailConfirmation tenham que ser iguais.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerCreateValidator.cs
> +                .WithMessage("Cpf is invalid");
Informar qual o formato válido esperado.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerCreateValidator.cs
> +                .Must(OverAgeCustomer).WithMessage("Customer must be at least 18 years old");
```suggestion
                .NotEmpty()
                .Must(OverAgeCustomer)
                .WithMessage("Customer must be at least 18 years old");
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerCreateValidator.cs
> +                .Must(OverAgeCustomer).WithMessage("Customer must be at least 18 years old");
Não tem necessidade de colocar mensagem no NotEmpty(), o próprio já tem uma mensagem padrão.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerRulesValidator.cs
> +﻿using DomainModels.Entities;
Pode excluir essa classe. Só precisa pro Create e pro Update.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerUpdateValidator.cs
> +﻿using AppModels;
Aplicar os mesmos comentários do Create aqui.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +
```suggestion
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +
A princípio esses outros packages não são necessários aqui, apenas na AppService.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        }
```suggestion
    public class CostumerController : ControllerBase
    {
        private readonly ICustomerAppService _customerAppService;
        
        public CostumerController(ICustomerAppService customerAppService)
        {
            _customerAppService = customerAppService ?? throw new ArgumentNullException(nameof(customerAppService));
        }
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +        }
Alterar ao longo da controller.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +        builder.Services.AddControllers();
```suggestion
var builder = WebApplication.CreateBuilder(args);

        builder.Services.AddControllers();
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/DomainServices/DomainServices.csproj
> +    <ProjectReference Include="..\AppModels\AppModels.csproj" />
```suggestion
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/DomainServices/DomainServices.csproj
> +    <ProjectReference Include="..\AppModels\AppModels.csproj" />
A camada de Domain não tem acesso a camada de Application.

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/DomainServices/Services/CustomerService.cs
> +        public void Create(CustomerEntity customerCreate)
```suggestion
        private readonly List<CustomerEntity> listCustomers = new();
        
        public void Create(CustomerEntity customerCreate)
```

2022-12-06 20:37 UTC, gregoryzimmerwarren commented on ApiEverest/DomainServices/Services/CustomerService.cs
> +}
```suggestion
        }
    }
}
```

2022-12-07 13:29 UTC, gregoryzimmerwarren requested changes
Fiz mais algumas alterações. Qualquer dúvida só entrar em contato.

2022-12-07 13:29 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Profiles/CustomerProfile.cs
> +    }
```suggestion
using DomainModels.Entities;

namespace ApiEverest.Profiles
{
    public class CustomerProfile : Profile
    {
        public CustomerProfile() 
        {
            CreateMap<CustomerCreateDto, CustomerEntity>();
            CreateMap<CustomerUpdateDto, CustomerEntity>();
            CreateMap<CustomerEntity, CustomerResultDto>();
        }
    }
```

2022-12-07 13:29 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerCreateValidator.cs
> +                .EmailAddress(EmailValidationMode.Net4xRegex)
```suggestion
                .NotEmpty()
                .EmailAddress(EmailValidationMode.Net4xRegex)
```

2022-12-07 13:29 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerUpdateValidator.cs
> +                .EmailAddress(EmailValidationMode.Net4xRegex)
```suggestion
            RuleFor(customer => customer.Email)
                .NotEmpty()
                .EmailAddress(EmailValidationMode.Net4xRegex)
```

2022-12-07 13:29 UTC, gregoryzimmerwarren commented on ApiEverest/AppServices/Validators/CustomerUpdateValidator.cs
> +                .Must(OverAgeCustomer).WithMessage("Customer must be at least 18 years old");
```suggestion
                .WithMessage("date of birth must be informed")
                .Must(OverAgeCustomer)
                .WithMessage("Customer must be at least 18 years old");
```

2022-12-07 13:29 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +        builder.Services.AddAutoMapper(Assembly.Load(nameof(AppServices)));
```suggestion
        builder.Services.AddSingleton<ICustomerService, CustomerService>();
        builder.Services.AddTransient<ICustomerAppService, CustomerAppService>();
        builder.Services.AddValidatorsFromAssembly(Assembly.Load(nameof(AppServices)));
        builder.Services.AddAutoMapper(Assembly.Load(nameof(AppServices)));
```

2022-12-07 13:29 UTC, gregoryzimmerwarren commented on ApiEverest/CrudApi/Program.cs
> +        builder.Services.AddAutoMapper(Assembly.Load(nameof(AppServices)));
Usa o Ctrl+K+D pra confirmar a indentação.

2022-12-07 13:53 UTC, gregoryzimmerwarren approved these changes

2022-12-15 12:26 UTC, LuanFortunatoW approved these changes

2022-12-20 13:16 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +using DomainServices.Services;
```suggestion
using AutoMapper;
using DomainModels.Entities;
using DomainServices.Services;
```
Remover usings não utilizados. CTRL + R + G

2022-12-20 13:22 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/Controllers/CostumerController.cs
> +                return Created("Id:", _customerAppService);
```suggestion
                _customerAppService.Create(customerEntity);
                return Created("Id:", _customerAppService);
```
Você está retonando ICustomerAppService não acho que é isso que você quer retornar. Deveria pegar o retorno da linha 51 (o CustomerId) e colocar dentro do Created

2022-12-20 13:36 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
> +        }
```suggestion
        }
        
```

2022-12-20 13:36 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
> +        }
```suggestion
        }
        
```

2022-12-20 13:37 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
> +        }
```suggestion
        }
        
```

2022-12-20 13:37 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
> +        }
```suggestion
        }
        
```

2022-12-20 13:37 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/CustomerService.cs
> +        }
```suggestion
        }
        
```

2022-12-20 13:38 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/Services/ICustomerService.cs
> +        void Create(CustomerEntity model);
```suggestion
        long Create(CustomerEntity model);
```

2022-12-20 13:40 UTC, santosclaudinei-warren commented on ApiEverest/CrudApi/ApiEverest.csproj
> +	  <ProjectReference Include="..\AppServices\AppServices.csproj" />
```suggestion
	  <ProjectReference Include="..\AppServices\AppServices.csproj" />
```
Corrigir indentação com CTRL + K + D

2022-12-20 13:42 UTC, santosclaudinei-warren commented on ApiEverest/DomainServices/DomainServices.csproj
> +  </ItemGroup>
```suggestion
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainModels\DomainModels.csproj" />
  </ItemGroup>
```
Corrigir indentação com CTRL + K + D

2022-12-20 13:43 UTC, santosclaudinei-warren commented on ApiEverest/DomainModels/DomainModels.csproj
> +  </PropertyGroup>
```suggestion
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
```

Corrigir indentação com CTRL + K + D

2022-12-20 13:44 UTC, santosclaudinei-warren commented on ApiEverest/DomainModels/Entities/CustomerEntity.cs
> +        }
```suggestion
        }
        
```

2022-12-20 13:45 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/AppModels.csproj
> +  </PropertyGroup>
```suggestion
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
```
Corrigir indentação com CTRL + K + D

2022-12-20 13:46 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +        {
```suggestion
          int number
        )
        {
```

2022-12-20 13:47 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerCreateDto.cs
> +        }
```suggestion
        }
        
```

2022-12-20 13:47 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerResultDto.cs
> +        {
```suggestion
        string postalCode
        )
        {
```

2022-12-20 13:47 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerResultDto.cs
> +        }
```suggestion
        }
        
```

2022-12-20 13:48 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +        {
```suggestion
          int number
        )
        {
```

2022-12-20 13:48 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerUpdateDto.cs
> +        }
```suggestion
        }
        
```

2022-12-20 13:50 UTC, santosclaudinei-warren commented on ApiEverest/AppModels/CustomerResultDto.cs
> +            Id = Id;
```suggestion
            Id = id;
```

2022-12-20 17:23 UTC, SuelenLaffinWarren commented
Ajustes realizados

2022-12-21 14:04 UTC, santosclaudinei-warren approved these changes

2022-12-21 14:06 UTC, merged